ade20k_root: /gpfs/helios/home/soliman/logic_explained_networks/data/ade20k/ADEChallengeData2016/
chosen_classes:
- street
- bedroom
- living_room
- bathroom
- kitchen
- skyscraper
- highway
device: cuda
dino_model: facebook/dinov2-base
embedding_dim: 2816
epochs: 2000
global_rules_path: ./ade20k_BRL_50c_4cl_20250506_202030_global_rules.pkl
global_weights_path: ./ade20k_BRL_50c_4cl_20250506_202030_global_weights.pkl
kmeans_rounds: 2
label_path: /path/to/labels.npy
lens_method: General
logs_dir: ./logs/ade20k_BRL_50c_4cl_20250506_202030.metrics.csv
min_detector_score: 0.9
min_mask_pixels: 5000
num_classes: 7
num_clients: 4
num_clusters: 50
phase2_rounds: 5
processed_dataset_root: /gpfs/helios/home/soliman/logic_explained_networks/data/ade20k/ADEChallengeData2016/images/
rule_rounds: 5
run_id: '20250506_202030'
sam_cfg: configs/sam2.1/sam2.1_hiera_t.yaml
sam_ckpt: /gpfs/helios/home/soliman/logic_explained_networks/experiments/sam2.1_hiera_tiny.pt
scene_cat_file: /gpfs/helios/home/soliman/logic_explained_networks/data/ade20k/ADEChallengeData2016/sceneCategories.txt
seed: 42
segment_cache_dir: ./segment_cache_ade20k_BRL_50c_4cl_20250506_202030
segment_save_dir: ./segments_ade20k_BRL_50c_4cl_20250506_202030
subset: training
weight_epsilon: 0.001
